import 'package:flutter/material.dart';
import 'package:pokeflutter/ui/home/pokemon_view_model.dart';
import 'package:provider/provider.dart';

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    // We observe our updated PokemonViewModel
    final pokemonViewModel = Provider.of<PokemonViewModel>(context);

    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Center(
          child: Text(widget.title),
        ),
      ),
      body: renderBodyContent(pokemonViewModel),
      floatingActionButton: FloatingActionButton(
        // 1. New Event: We trigger our asynchronous network call
        onPressed: pokemonViewModel.getCompletePokemon,
        child: const Icon(Icons.add),
      ),
    );
  }

  Widget renderBodyContent(PokemonViewModel pokemonViewModel) {
    // 2. We extract the pure domain state from the ViewModel
    final pokemon = pokemonViewModel.pokemonState;

    return Center(
      child: SingleChildScrollView(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            if (pokemon != null) ...[
              // We render the image generated by the UseCase
              Image.network(
                pokemon.urlImage,
                height: 200,
              ),
              const SizedBox(height: 16),
              // Golden Rule Verification: Showing raw domain data in UI!
              Padding(
                padding: const EdgeInsets.all(16.0),
                child: Text(
                  pokemon.toString(),
                  textAlign: TextAlign.center,
                  style: Theme.of(context).textTheme.bodyMedium,
                ),
              ),
            ] else
              const Text('Waiting for a Pokemon...'),
          ],
        ),
      ),
    );
  }
}
