import 'package:flutter/material.dart';
import 'package:pokeflutter/ui/home/my_home_page.dart';
import 'package:pokeflutter/ui/theme/pokedex_colors.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    // Exact mapping of your Android LightColorScheme
    final lightColorScheme = ColorScheme.light(
      primary: PokedexColors.pokedexRed,
      secondary: PokedexColors.pokeballBlue,
      surface: Colors.white,
      surfaceContainerHighest:
          const Color(0xFFEBEBEB), // Matching MaterialTheme surfaceVariant
      onSurfaceVariant: const Color(0xFF49454F),
    );

    // Exact mapping of your Android DarkColorScheme
    final darkColorScheme = ColorScheme.dark(
      primary: PokedexColors.lightRed,
      secondary: PokedexColors.lightBlue,
      surface: PokedexColors.darkCharcoal,
      surfaceContainerHighest: const Color(0xFF303030),
      onSurfaceVariant: const Color(0xFFCAC4D0),
    );

    return MaterialApp(
      title: 'PokeFlutter',
      debugShowCheckedModeBanner: false,

      // 1. Register the autogenerated localization delegates
      localizationsDelegates: AppLocalizations.localizationsDelegates,

      // 2. Define the supported locales imported from your .arb files
      supportedLocales: AppLocalizations.supportedLocales,

      theme: ThemeData(
        useMaterial3: true,
        colorScheme: lightColorScheme,
      ),
      darkTheme: ThemeData(
        useMaterial3: true,
        colorScheme: darkColorScheme,
      ),
      themeMode: ThemeMode.system,
      home: const MyHomePage(title: 'PokeFlutter v0.3'),
    );
  }
}
